"""text_editor_app - Application Desktop de Traitement de Texte.

Generated by VisionIT Framework
Application desktop avec fenêtre native
"""

from nicegui import ui, app
from pathlib import Path
import json
from datetime import datetime

# Configuration de la fenêtre desktop
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
WINDOW_TITLE = "Éditeur de Texte - VisionIT"


@ui.page("/")
def editor_page():
    """Page principale - Éditeur de texte."""
    
    # Variable pour stocker le texte actuel
    current_text = {"value": ""}
    current_file = {"path": None}
    
    # === BARRE DE MENU ===
    with ui.header().classes('w-full bg-blue-600 text-white p-2'):
        with ui.row().classes('w-full items-center gap-4'):
            # Titre
            ui.icon("description", size="24px")
            ui.label("Éditeur de Texte").classes("text-lg font-bold")
            
            ui.separator().classes('mx-4 h-6')
            
            # Boutons de la barre d'outils
            def new_file():
                text_area.value = ""
                current_file["path"] = None
                status_label.set_text("Nouveau document")
            
            def save_file():
                content = text_area.value
                if current_file["path"]:
                    with open(current_file["path"], 'w', encoding='utf-8') as f:
                        f.write(content)
                    status_label.set_text(f"Sauvegardé: {current_file['path']}")
                    ui.notify("Fichier sauvegardé !", color="positive", position="bottom-center")
                else:
                    save_as_file()
            
            def save_as_file():
                # Pour une vraie app, on utiliserait une dialog de fichier
                default_path = Path.home() / f"document_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
                current_file["path"] = default_path
                with open(current_file["path"], 'w', encoding='utf-8') as f:
                    f.write(text_area.value)
                status_label.set_text(f"Sauvegardé: {current_file['path']}")
                ui.notify(f"Fichier sauvegardé: {current_file['path']}", color="positive", position="bottom-center", timeout=3000)
            
            def open_file():
                # Simulation d'ouverture de fichier
                ui.notify("Utilisez la zone de texte pour éditer", color="info", position="bottom-center")
            
            # Boutons
            ui.button("Nouveau", icon="add", on_click=new_file).props('flat color=white')
            ui.button("Ouvrir", icon="folder_open", on_click=open_file).props('flat color=white')
            ui.button("Sauvegarder", icon="save", on_click=save_file).props('flat color=white')
            
            ui.separator().classes('mx-4 h-6')
            
            # Stats
            word_count = ui.label("Mots: 0").classes('text-sm')
            char_count = ui.label("Caractères: 0").classes('text-sm')
    
    # === ZONE PRINCIPALE ===
    with ui.column().classes('w-full flex-1 p-4'):
        
        # Zone d'édition de texte
        ui.label("Zone d'édition").classes("text-lg font-semibold mb-2")
        
        text_area = ui.textarea() \
            .classes('w-full') \
            .props('outlined autogrow max-height=600') \
            .style('height: 500px; font-family: monospace; font-size: 14px;')
        
        # Fonction pour mettre à jour les stats
        def update_stats(e):
            text = e.value
            words = len(text.split())
            chars = len(text)
            word_count.set_text(f"Mots: {words}")
            char_count.set_text(f"Caractères: {chars}")
        
        text_area.on('change', update_stats)
        text_area.on('blur', update_stats)
        
        # === BARRE D'OUTILS ===
        ui.label("Formatage").classes("text-lg font-semibold mt-4 mb-2")
        
        with ui.row().classes('w-full gap-2'):
            # Le texte dans NiceGUI ne supporte pas le formatage riche nativement
            # Mais on peut ajouter des boutons d'action
            def insert_bold():
                text_area.value += "**texte** "
            
            def insert_italic():
                text_area.value += "*texte* "
            
            def insert_list():
                text_area.value += "\n- Item "
            
            def insert_code():
                text_area.value += "`code` "
            
            ui.button("Gras", icon="format_bold", on_click=insert_bold).props('outline')
            ui.button("Italique", icon="format_italic", on_click=insert_italic).props('outline')
            ui.button("Liste", icon="format_list_bulleted", on_click=insert_list).props('outline')
            ui.button("Code", icon="code", on_click=insert_code).props('outline')
            
            ui.separator().classes('mx-4')
            
            def copy_text():
                ui.clipboard.write(text_area.value)
                ui.notify("Texte copié !", color="positive", position="bottom-center")
            
            def clear_text():
                text_area.value = ""
                word_count.set_text("Mots: 0")
                char_count.set_text("Caractères: 0")
            
            ui.button("Copier", icon="content_copy", on_click=copy_text).props('outline')
            ui.button("Effacer", icon="delete", on_click=clear_text).props('outline color=red')
        
        # === ZONE D'INFORMATION ===
        with ui.card().classes('w-full mt-4 p-4 bg-gray-50'):
            ui.label("📝 Éditeur de Texte VisionIT").classes("text-lg font-bold mb-2")
            ui.markdown("""
            **Fonctionnalités:**
            - Édition de texte simple
            - Compteur de mots et caractères
            - Sauvegarde de fichiers
            - Interface moderne avec Tailwind CSS
            
            **Raccourcis:**
            - Ctrl+S : Sauvegarder (dans une vraie app)
            - Ctrl+N : Nouveau document
            """)
    
    # === BARRE DE STATUS ===
    status_label = ui.label("Prêt").classes('text-sm text-gray-600')
    with ui.footer().classes('w-full bg-gray-100 p-2'):
        with ui.row().classes('w-full justify-between'):
            status_label
            ui.label(f"VisionIT Framework v0.1.0").classes('text-sm text-gray-500')


# Configuration de l'application
def configure_app():
    """Configurer l'application desktop."""
    
    # Définir le titre de la fenêtre
    app.native.title = WINDOW_TITLE
    app.native.width = WINDOW_WIDTH
    app.native.height = WINDOW_HEIGHT
    app.native.resizable = True
    app.native.fullscreen = False
    
    # Position de la fenêtre (centrée)
    app.native.window_pos = (100, 100)


if __name__ == "__main__":
    # Configuration
    configure_app()
    
    # Lancement en mode NATIF (fenêtre desktop)
    ui.run(
        title=WINDOW_TITLE,
        host="127.0.0.1",
        port=8080,
        reload=False,
        native=True,  # ⭐ MODE FENÊTRE DESKTOP ⭐
        window_size=(WINDOW_WIDTH, WINDOW_HEIGHT),
        fullscreen=False,
        frameless=False,
    )
