"""test_final - Application Desktop.

Generated by VisionIT Framework
Application desktop avec fenêtre native
"""

from nicegui import ui, app
from pathlib import Path
import json
import sys

# === CONFIGURATION DE LA FENÊTRE ===
WINDOW_TITLE = "test_final"
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 800
PORT = 8080


# Helper pour les ressources (compatible PyInstaller)
def get_resource_path(relative_path: str) -> Path:
    """Get absolute path to resource, works for dev and PyInstaller."""
    if hasattr(sys, "_MEIPASS"):
        base_path = Path(sys._MEIPASS)
    else:
        base_path = Path(__file__).parent
    return base_path / relative_path


# Chargement des infos projet
INFO_FILE = get_resource_path("info.json")
with open(INFO_FILE, "r", encoding="utf-8") as f:
    project_info = json.load(f)


@ui.page("/")
def index():
    """Page d'accueil."""
    
    # Configuration des couleurs
    ui.colors(primary='#2563eb', secondary='#64748b', accent='#8b5cf6')
    
    # En-tête
    with ui.header().classes('w-full bg-blue-600 text-white'):
        with ui.row().classes('w-full items-center px-4 py-2'):
            ui.icon("home", size="28px")
            ui.label("test_final").classes("text-xl font-bold ml-2")
            ui.label(f"v{project_info.get('version', '1.0.0')}").classes("text-sm ml-4 opacity-90")
    
    # Contenu principal
    with ui.column().classes('w-full p-6 gap-6'):
        
        # Message de bienvenue
        with ui.card().classes('w-full p-6 bg-green-50 border-l-4 border-green-500'):
            ui.label("✅ Application Démarrée avec Succès !").classes("text-2xl font-bold text-green-700")
            ui.label("Votre application desktop VisionIT est fonctionnelle.").classes("text-gray-700 mt-2")
        
        # Informations du projet
        with ui.card().classes('w-full p-6'):
            ui.label("📋 Informations du Projet").classes("text-xl font-semibold mb-4")
            
            with ui.grid().classes('grid-cols-3 gap-4'):
                with ui.card().classes('p-4 bg-blue-50'):
                    ui.label("Application").classes("text-gray-600 text-sm")
                    ui.label(project_info.get('project_name', 'N/A')).classes("text-lg font-bold text-blue-600")
                
                with ui.card().classes('p-4 bg-green-50'):
                    ui.label("Auteur").classes("text-gray-600 text-sm")
                    ui.label(project_info.get('author', 'N/A')).classes("text-lg font-bold text-green-600")
                
                with ui.card().classes('p-4 bg-purple-50'):
                    ui.label("Version").classes("text-gray-600 text-sm")
                    ui.label(project_info.get('version', '1.0.0')).classes("text-lg font-bold text-purple-600")
        
        # Section interactive
        with ui.card().classes('w-full p-6'):
            ui.label("🎮 Interactive").classes("text-xl font-semibold mb-4")
            
            with ui.row().classes('gap-4 flex-wrap'):
                ui.button("👍 Test", color="primary") \
                  .on('click', lambda: ui.notify("✅ Ça fonctionne !", color="positive", position="top"))
                
                ui.button("✅ Succès", color="positive") \
                  .on('click', lambda: ui.notify("🎉 Réussi !", color="positive"))
                
                ui.button("⚠️ Warning", color="warning") \
                  .on('click', lambda: ui.notify("⚠️ Attention !", color="warning"))
            
            with ui.row().classes('w-full mt-4 gap-4'):
                ui.input("Nom", placeholder="Votre nom").classes('flex-1')
                ui.input("Email", placeholder="email@exemple.com").classes('flex-1')
        
        # Features
        with ui.row().classes('w-full gap-4'):
            with ui.card().classes('flex-1 p-6 text-center'):
                ui.icon("desktop_windows", size="64px").classes("text-blue-600")
                ui.label("Fenêtre Native").classes("text-lg font-semibold mt-2")
            
            with ui.card().classes('flex-1 p-6 text-center'):
                ui.icon("palette", size="64px").classes("text-green-600")
                ui.label("UI Moderne").classes("text-lg font-semibold mt-2")
            
            with ui.card().classes('flex-1 p-6 text-center'):
                ui.icon("build", size="64px").classes("text-purple-600")
                ui.label("Exécutable").classes("text-lg font-semibold mt-2")
    
    # Pied de page
    with ui.footer().classes('w-full bg-gray-100'):
        with ui.row().classes('w-full justify-between px-4 py-2'):
            ui.label(f"© 2024 {project_info.get('author', 'VisionIT')}").classes('text-gray-600 text-sm')
            ui.label("✅ VisionIT Framework").classes('text-green-600 font-bold text-sm')


if __name__ == "__main__":
    print("\n" + "="*60)
    print(f"🚀 LANCEMENT DE test_final")
    print("="*60)
    print(f"📝 Titre: {WINDOW_TITLE}")
    print(f"📐 Taille: {WINDOW_WIDTH}x{WINDOW_HEIGHT}")
    print(f"🌐 Port: {PORT}")
    print(f"🖥️  Mode: Fenêtre Desktop Native")
    print("="*60)
    print("\n⏳ Ouverture de la fenêtre...\n")
    
    # Configuration native
    app.native.title = WINDOW_TITLE
    app.native.width = WINDOW_WIDTH
    app.native.height = WINDOW_HEIGHT
    
    # Lancement avec fenêtre native
    ui.run(
        title=WINDOW_TITLE,
        host="127.0.0.1",
        port=PORT,
        reload=False,
        show=True,
        native=True,  # ⭐ FENÊTRE DESKTOP ⭐
        window_size=(WINDOW_WIDTH, WINDOW_HEIGHT),
        fullscreen=False,
        frameless=False,
    )
